SET search_path TO plantour, public;

begin;

delete from sitemap_urls;

insert into sitemap_urls (url, last_modified, priority, is_active)
values
	('/', now(), 80, true),
	('/packing-list-generator', now(), 70, true),
	('/packing-list-generator/templates', now(), 70, true),
	('/sign-up', now(), 40, true),
	('/help', now(), 60, true),
	('/help/account', now(), 55, true),
	('/help/account/login', now(), 50, true),
	('/help/account/profile', now(), 50, true),
	('/help/ai-recommendations', now(), 55, true),
	('/help/ai-recommendations/add-to-dictionary', now(), 50, true),
	('/help/ai-recommendations/add-to-trip-own', now(), 50, true),
	('/help/ai-recommendations/add-to-trip-shared', now(), 50, true),
	('/help/ai-recommendations/ask-ai', now(), 50, true),
	('/help/filtering-sorting', now(), 55, true),
	('/help/filtering-sorting/clear-filters', now(), 50, true),
	('/help/filtering-sorting/filters-intro', now(), 50, true),
	('/help/filtering-sorting/search', now(), 50, true),
	('/help/filtering-sorting/sort-items', now(), 50, true),
	('/help/get-started', now(), 55, true),
	('/help/get-started/create-account', now(), 50, true),
	('/help/get-started/test-mode', now(), 50, true),
	('/help/get-started/welcome', now(), 50, true),
	('/help/landing-dashboard', now(), 55, true),
	('/help/landing-dashboard/dashboard-overview', now(), 50, true),
	('/help/landing-dashboard/landing-explained', now(), 50, true),
	('/help/landing-dashboard/trip-all-users-info', now(), 50, true),
	('/help/landing-dashboard/trip-user-info', now(), 50, true),
	('/help/overview', now(), 55, true),
	('/help/overview/admins-and-participants', now(), 50, true),
	('/help/overview/basic-workflow', now(), 50, true),
	('/help/overview/key-features', now(), 50, true),
	('/help/overview/what-is-plantour', now(), 50, true),
	('/help/overview/who-is-it-for', now(), 50, true),
	('/help/packs', now(), 55, true),
	('/help/packs/add-bag', now(), 50, true),
	('/help/packs/delete-bag', now(), 50, true),
	('/help/packs/edit-bag', now(), 50, true),
	('/help/packs/filter-packs', now(), 50, true),
	('/help/packs/packs-intro', now(), 50, true),
	('/help/planning-tips', now(), 55, true),
	('/help/planning-tips/cant-delete', now(), 50, true),
	('/help/planning-tips/common-problems', now(), 50, true),
	('/help/planning-tips/error-messages', now(), 50, true),
	('/help/planning-tips/faq', now(), 50, true),
	('/help/planning-tips/faq-account', now(), 50, true),
	('/help/planning-tips/faq-collaboration', now(), 50, true),
	('/help/planning-tips/faq-general', now(), 50, true),
	('/help/planning-tips/faq-packing', now(), 50, true),
	('/help/planning-tips/faq-trips', now(), 50, true),
	('/help/planning-tips/missing-items', now(), 50, true),
	('/help/shared-things', now(), 55, true),
	('/help/shared-things/accept-shared-item', now(), 50, true),
	('/help/shared-things/assign-shared-item', now(), 50, true),
	('/help/shared-things/create-shared-item', now(), 50, true),
	('/help/shared-things/delete-shared-item', now(), 50, true),
	('/help/shared-things/edit-shared-item', now(), 50, true),
	('/help/shared-things/finish-shared-item', now(), 50, true),
	('/help/shared-things/reject-shared-item', now(), 50, true),
	('/help/shared-things/shared-intro', now(), 50, true),
	('/help/shared-things/unassign-shared-item', now(), 50, true),
	('/help/templates', now(), 55, true),
	('/help/templates/item-templates', now(), 50, true),
	('/help/templates/public-templates', now(), 50, true),
	('/help/templates/templates-intro', now(), 50, true),
	('/help/things', now(), 55, true),
	('/help/things/add-item', now(), 50, true),
	('/help/things/delete-item', now(), 50, true),
	('/help/things/edit-item', now(), 50, true),
	('/help/things/filter-things', now(), 50, true),
	('/help/things/item-categories', now(), 50, true),
	('/help/things/things-intro', now(), 50, true),
	('/help/travelers', now(), 55, true),
	('/help/travelers/add-traveler', now(), 50, true),
	('/help/travelers/delete-traveler', now(), 50, true),
	('/help/travelers/edit-traveler', now(), 50, true),
	('/help/travelers/filter-travelers', now(), 50, true),
	('/help/travelers/travelers-intro', now(), 50, true),
	('/help/trip-comments', now(), 55, true),
	('/help/trip-comments/add-comment', now(), 50, true),
	('/help/trip-comments/comments-intro', now(), 50, true),
	('/help/trip-packs', now(), 55, true),
	('/help/trip-packs/add-bag-to-trip', now(), 50, true),
	('/help/trip-packs/edit-trip-bag', now(), 50, true),
	('/help/trip-packs/remove-bag-from-trip', now(), 50, true),
	('/help/trip-packs/trip-packs-intro', now(), 50, true),
	('/help/trip-participants', now(), 55, true),
	('/help/trip-participants/add-participant', now(), 50, true),
	('/help/trip-participants/participant-permissions', now(), 50, true),
	('/help/trip-participants/participants-intro', now(), 50, true),
	('/help/trip-participants/remove-participant', now(), 50, true),
	('/help/trips', now(), 55, true),
	('/help/trips/create-trip', now(), 50, true),
	('/help/trips/delete-trip', now(), 50, true),
	('/help/trips/edit-trip', now(), 50, true),
	('/help/trips/filter-trips', now(), 50, true),
	('/help/trips/select-current-trip', now(), 50, true),
	('/help/trips/trip-status', now(), 50, true),
	('/help/trips/trips-intro', now(), 50, true);


commit;